# Xamarin.Android and Xamarin.iOS
# Build a Xamarin.Android and Xamarin.iOS app.
# Add steps that test, sign, and distribute the app, save build artifacts, and more:
# https://learn.microsoft.com/azure/devops/pipelines/ecosystems/xamarin

jobs:

- job: XamarinFormsBuild
  pool:
    vmImage: 'macos-13'

  variables:
    buildConfiguration: 'Debug'
    outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

  steps:

  - task: Bash@3
    displayName: Install Xamarin Components
    inputs:
      targetType: 'inline'
      script: |
        brew install --cask xamarin-ios
        brew install --cask xamarin-android
  
  # - task: Bash@3
  #   displayName: Install Xamarin Components
  #   inputs:
  #     targetType: 'inline'
  #     script: |
  #       chmod +x install_xam.sh
  #       ./install_xam.sh
      
  - task: CmdLine@2
    displayName: Set Xcode Version
    inputs:
      script: '/bin/bash -c "echo ''##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]''/Applications/Xcode_15.2.app;sudo xcode-select --switch /Applications/Xcode_15.2.app/Contents/Developer"'
  
  - task: NuGetCommand@2
    displayName: Restore Nugets
    inputs:
      command: 'restore'
      restoreSolution: 'BuildVMApp.sln'
      feedsToUse: 'select'

  - task: XamarinAndroid@1
    displayName: Build Xamarin Android
    inputs:
      projectFile: 'BuildVMApp/BuildVMApp.Android/BuildVMApp.Android.csproj'
      configuration: '$(buildConfiguration)'
      msbuildVersionOption: 'latest'
      jdkOption: 'JDKVersion'

  - task: XamariniOS@2
    displayName: Build Xamarin iOS
    inputs:
      solutionFile: 'BuildVMApp.sln'
      configuration: 'Debug'
      packageApp: false
      buildForSimulator: true
      runNugetRestore: false